name: Acquire latest stock levels from NHSBT website

on:
  push:
    branches:
      - main
    schedule:
      - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Python
      uses: actions/setup-python@v4
      with:
        python_version: '3.9'
        cache: 'pip'
    - name: PIP
      run: pip install -r requirements.txt
    - name: Acquire
      run: nhsbt_acquire
    - name: Commit
      run: |-
        git config --global user.name "nhsbt-blood-levels"
        git config --global user.email "nhsbt-blood-levels@svenlatham.com"
        git add nhsbt.txt && git commit -m "Updated NHSBT blood levels"
        git push