name: Update GitHub Pages with Charts

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1am
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas plotly jinja2

    - name: Generate charts and pages
      run: python create-page.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/
        git commit -m "Daily update of charts and pages"
        git push
